name: test
on: 
    push:
        branches: 
            - main
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7.0.1
            - name: check repo
              run: ls -la
